---
name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Use NodeJS ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Copy files to another respository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{secrets.DEPLOY_SSH_KEY}}
        with:
          user-email:
          create-target-branch-if-needed: true
          source-directory: "dist"
          destination-github-username: ${{ secrets.DEPLOY_GITHUB_USERNAME }}
          destination-repository-name: ${{ secrets.DEPLOY_GITHUB_REPOSITORY }}
